require "../../spec_helper"

private def strict_semantic(code, root = "/strict", filename = "/strict/main.cr")
  semantic(code, filename: filename, strict_signatures_root: root)
end

private def assert_strict_type(code, file = __FILE__, line = __LINE__, &)
  result = strict_semantic(code)
  program = result.program
  expected_type = with program yield program
  node = result.node
  node = node.last if node.is_a?(Expressions)
  node.type.should eq(expected_type), file: file, line: line
end

describe "Semantic: strict signatures" do
  it "gives callers the declared return type, not the body's" do
    assert_strict_type(<<-CRYSTAL) { union_of(int32, char) }
      def foo : Int32 | Char
        1
      end

      foo
      CRYSTAL
  end

  it "keeps the body's type outside strict mode" do
    assert_type(<<-CRYSTAL) { int32 }
      def foo : Int32 | Char
        1
      end

      foo
      CRYSTAL
  end

  it "keeps the body's type for code outside the strict root" do
    result = strict_semantic(<<-CRYSTAL, filename: "/elsewhere/main.cr")
      def foo : Int32 | Char
        1
      end

      foo
      CRYSTAL
    result.node.as(Expressions).last.type.should eq(result.program.int32)
  end

  it "keeps the body's type for code in the root's lib" do
    result = strict_semantic(<<-CRYSTAL, filename: "/strict/lib/shard/src/shard.cr")
      def foo : Int32 | Char
        1
      end

      foo
      CRYSTAL
    result.node.as(Expressions).last.type.should eq(result.program.int32)
  end

  it "widens to the virtual type of a declared class" do
    assert_strict_type(<<-CRYSTAL) { types["Animal"].virtual_type! }
      abstract class Animal
      end

      class Dog < Animal
      end

      class Cat < Animal
      end

      def pet : Animal
        Dog.new
      end

      pet
      CRYSTAL
  end

  it "keeps NoReturn" do
    assert_strict_type(<<-CRYSTAL) { no_return }
      lib LibFoo
        fun exit : NoReturn
      end

      def foo : Int32
        LibFoo.exit
      end

      foo
      CRYSTAL
  end

  it "keeps the body's type for a generic restriction without type arguments" do
    assert_strict_type(<<-CRYSTAL) { generic_class "Foo", int32 }
      class Foo(T)
      end

      def foo : Foo
        Foo(Int32).new
      end

      foo
      CRYSTAL
  end

  it "still errors when the body doesn't match the declared type" do
    expect_raises(Crystal::TypeException, "method ::foo must return Int32 but it is returning Char") do
      strict_semantic(<<-CRYSTAL)
        def foo : Int32
          'a'
        end

        foo
        CRYSTAL
    end
  end

  # https://forum.crystal-lang.org/t/8718/10: upstream, `foo(3)` is an
  # `Int32` until the body returns `nil`, then callers break. Here they see
  # `Int32?` either way, so a body edit can't break them.
  it "makes callers handle a declared nil the body doesn't return" do
    expect_raises(Crystal::TypeException, "undefined method 'succ' for Nil") do
      strict_semantic(<<-CRYSTAL)
        struct Int32
          def succ : Int32
            self
          end
        end

        def foo(x : Int32) : Int32?
          x
        end

        foo(3).succ
        CRYSTAL
    end
  end

  it "errors on methods without a return type" do
    expect_raises(Crystal::TypeException, "strict signatures: 2 methods without a return type") do
      strict_semantic(<<-CRYSTAL)
        class Foo
          def initialize
          end

          def bar
            1
          end

          def self.baz
            2
          end

          def qux : Int32
            3
          end
        end
        CRYSTAL
    end
  end

  it "doesn't require a return type for methods generated by macros" do
    strict_semantic(<<-CRYSTAL)
      macro define_foo
        def foo
          1
        end
      end

      define_foo
      foo
      CRYSTAL
  end
end
